### ISSUE TITLE
Bump version again?

### ISSUE THREAD

**Issue by pmiddend** [Sentenai/ascii-table#2]
I like your library! However, I cannot use it right now because it conflicts withe my aeson version >=1.3. I see you already fixed that, so would you mind bumping the version and uploading it to hackage again?

**Comment by jezen** [comment]
Had exactly the same issue. Version bump would be handy. Let us know if we can help with this.

**Comment by mitchellwrosen** [comment]
Sure thing, I will upload a new version once CI passes.

**Comment by mitchellwrosen** [comment]
https://hackage.haskell.org/package/ascii-table-0.3.0.2
